### ISSUE TITLE
Any plans to support m1?

### ISSUE THREAD

**Issue by donatoaz** [RubyData/docker-stacks#31]
I tried running on mac m1 and got core dumped.

I'm not sure whether this is a platform issue, and have not tried building the image locally (how can I do it?)

```
Exception in callback <TaskWakeupMethWrapper object at 0x4021a6f160>(<Future finished result=None>)
handle: <Handle <TaskWakeupMethWrapper object at 0x4021a6f160>(<Future finished result=None>)>
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: Cannot enter into task <Task pending name='Task-11' coro=<HTTP1ServerConnection._server_request_loop() running at /opt/conda/lib/python3.9/site-packages/tornado/http1connection.py:823> wait_for=<Future finished result=None> cb=[IOLoop.add_future.<locals>.<lambda>() at /opt/conda/lib/python3.9/site-packages/tornado/ioloop.py:688]> while another task <Task pending name='Task-36' coro=<MappingKernelManager.start_kernel() running at /opt/conda/lib/python3.9/site-packages/notebook/services/kernels/kernelmanager.py:176> cb=[IOLoop.add_future.<locals>.<lambda>() at /opt/conda/lib/python3.9/site-packages/tornado/ioloop.py:688]> is being executed.
Exception in callback <TaskWakeupMethWrapper object at 0x4021b0c5e0>(<Future finished result=None>)
handle: <Handle <TaskWakeupMethWrapper object at 0x4021b0c5e0>(<Future finished result=None>)>
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: Cannot enter into task <Task pending name='Task-8' coro=<HTTP1ServerConnection._server_request_loop() running at /opt/conda/lib/python3.9/site-packages/tornado/http1connection.py:823> wait_for=<Future finished result=None> cb=[IOLoop.add_future.<locals>.<lambda>() at /opt/conda/lib/python3.9/site-packages/tornado/ioloop.py:688]> while another task <Task pending name='Task-36' coro=<MappingKernelManager.start_kernel() running at /opt/conda/lib/python3.9/site-packages/notebook/services/kernels/kernelmanager.py:176> cb=[IOLoop.add_future.<locals>.<lambda>() at /opt/conda/lib/python3.9/site-packages/tornado/ioloop.py:688]> is being executed.
Operation not permitted (src/thread.cpp:309)
Operation not permitted (src/thread.cpp:309)
qemu: uncaught target signal 6 (Aborted) - core dumped
```

**Comment by mrkn** [comment]
@donatoaz Sorry for the late reply.  I don't want to restrict this project on the single platform.  The contributions to support platforms other than x86_64 are very welcome.

**Comment by ipepe** [comment]
For me this works on M1, I only have issue with #35

**Comment by mrkn** [comment]
Both jupyter/docker-stacks and rubylang/ruby support arm64 platform. I think we can support Apple M1. I'll work to do so.
